spring.application.name=backend
server.port=5050

# MYSQL CONNECTION
spring.datasource.url=jdbc:mysql://localhost:3306/inventory_db
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update


#THE MAXIMUM SIGN OF IMAGE THAT CAN BE UPLOADED
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

# Cloudinary Configuration
cloudinary.cloud-name=dfxrrfccn
cloudinary.api-key=814843311439437
cloudinary.api-secret=_8eBNbNEsLzzWoUItYff-JYdqW8

secreteJwtString=cbfu9348gt04hvrw0hv090sf8943h8g043g943u9gh65rj57yjr

# Gmail SMTP Configuration (thay b?ng email và app password th?c t?)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dainguyenduc060@gmail.com
spring.mail.password=klmn nzih drfe kbqd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true